#!/bin/bash

#Activate the conda environment
source ~/miniconda3/etc/profile.d/conda.sh
conda activate rna_seq

# configs
SRA_ID="demo"
THREADS=2


########################### Step 1: Running FastQC #######################################
##########################################################################################

#Make output directory
mkdir -p fastqc_reports

# Run FastQC report
echo "Running FastQC for $SRA_ID....."

fastqc "${SRA_ID}.fastq" -o fastqc_reports/ -t "$THREADS"

echo "FastQC Completed for $SRA_ID!!. Reports are in: fastqc_reports"


############################ Step 2 :Running Trimmomatic to trim ##############################
################################################################################################

##configs
TRIM_OUTDIR="/home/prajjwal/rna_seq/Trimmed_output"


#Adapter files
ADAPTER_SE="/home/prajjwal/rna_seq/adapters/TruSeq3-SE.fa"
ADAPTER_PE="/home/prajjwal/rna_seq/adapters/TruSeq3-PE.fa"


# Create output directory
mkdir -p "$TRIM_OUTDIR"

# Run Trimmomatic
echo "▶ Running Trimmomatic..."

trimmomatic SE -threads 4 -phred33 \
  "${SRA_ID}.fastq" \
  "${TRIM_OUTDIR}/${SRA_ID}_trimmed.fastq" \
  ILLUMINACLIP:"$ADAPTER_SE":2:30:10 \
  TRAILING:10

echo "✔ Trimmomatic finished successfully!"

############################## Step 3: Running FastQC on trimmed file ##########################
################################################################################################

#Path to trimmed file
# TRIM_OUTDIR is the path for trimmed file

TRIM_FASTQC_OUTPUT="/home/prajjwal/rna_seq/fastqc_reports/trim_fastqc_report"
#Make output directory
mkdir -p "${TRIM_FASTQC_OUTPUT}"

# Run FastQC report
echo "Running FastQC for $SRA_ID Trimmed file....."

fastqc "${TRIM_OUTDIR}/${SRA_ID}_trimmed.fastq" -o "${TRIM_FASTQC_OUTPUT}" -t "$THREADS"

echo "FastQC Completed for $SRA_ID trimmed file!!!. Reports in: ${TRIM_FASTQC_OUTPUT}"


################################## Step 4: Run Hisat2 ########################################
###############################################################################################

GENOME_INDICES="/home/prajjwal/rna_seq/hisat2/grch38/genome"  #I have downloaded it in hisat2 folder

# create output directory
mkdir -p alignments

echo "Running HISAT2 alignment for ${SRA_ID}_trimmed.fastq"

#Run HISAT2 and sort output to BAM file
hisat2 -p "$THREADS" \
 --no-unal \
 -q \
 -x "$GENOME_INDICES" \
  -U "${TRIM_OUTDIR}/${SRA_ID}_trimmed.fastq" \
  | samtools sort -@ 2 -o "alignments/${SRA_ID}.bam"

echo " HISAT2 finished. BAM file created at alignments/${SRA_ID}.bam"


